# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-20 21:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='team_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_code', to='login_registration.Users'),
        ),
    ]
