# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-20 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='team_code',
            field=models.CharField(default='testteam', max_length=60),
            preserve_default=False,
        ),
    ]
